### PR TITLE
Build the project via a bash script

### PR DESCRIPTION
**Pull request by Anth0rx**
I've just created a simple build script in bash. For me it seems to work fine. It would be awesome, if you tested it.

Regards
Anth0rx

### CODE REVIEW

**Comment by Taose** [comment]
Can you add an option to the cmake in that? You might want to specify that the Release build type is to be used.

Also, You should put a comment at the top of the code indicating when the code was written and for which commit. I would also leave information how to use it.

**Comment by Anth0rx** [comment]
Okay, I'm on it.
Regarding the comment: I don't understand why I should put the commit on. Since this is a PR the script should be well tested before it is merged so there is no point in writing for which commit it was intended.

**Comment by Taose** [comment]
You don't understand why you should put a comment on? 

It's quite simple really, in ten years time when someone comes back and looks at it, they will probably want to know what its purpose is and how it does it. 

As for which commit it was intended for, this can be important in recognizing whether the code is still relevant. For example some code further up the line could make the shell script completely redundant.

**Comment by Anth0rx** [comment]
Is there some sort of template for this or just something like.
```
Originally created for commit b2e46cd619c2589a99080aa12bb5f1209d24c61c
on 21.08.17
```

**Comment by Taose** [comment]
That'd do, of course a bit about what the shell script does wouldn't go amiss either.

**Comment by Anth0rx** [comment]
Okay understood.

**Comment by Anth0rx** [comment]
So I added a description? Is it okay that way?

**Comment by Taose** [comment]
Perfect. Now someone (probably me, when I get time) will have to test that out. :+1:

**Comment by Taose** [comment]
Seems to do exactly what it says on the tin. 

I have a suggestion for future development. Allow it to switch between different cmake build types, such as Release, Testing, Debug... though by default it *should* be Release.

**Comment by Anth0rx** [comment]
Okay, I'm on that.

**Pull request merged**
